"""
GroqProvider — fallback LLM provider (Llama models via Groq's fast inference).

Used automatically when GeminiProvider fails (quota, timeout, connection error,
5xx). Model name is configurable via GROQ_MODEL (default: llama-3.3-70b-versatile,
an inexpensive, capable open-weight model well suited as a fallback).
"""

from __future__ import annotations

import asyncio
import logging
import time
from typing import Optional, Sequence

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage, BaseMessage
from langchain_core.runnables import RunnableConfig

from .base import BaseLLMProvider, LLMProviderError, classify_error

log = logging.getLogger("finai_edge.copilot.llm.groq")

DEFAULT_TIMEOUT_S = 20.0
MAX_RETRIES = 1  # 1 retry after the first attempt = 2 attempts max


class GroqProvider(BaseLLMProvider):
    provider_name = "groq"

    def __init__(
        self,
        api_key: Optional[str],
        model: str,
        *,
        timeout_s: float = DEFAULT_TIMEOUT_S,
        max_retries: int = MAX_RETRIES,
        temperature: float = 0.3,
    ):
        self._api_key = api_key
        self._model_name = model
        self._timeout_s = timeout_s
        self._max_retries = max_retries
        self._temperature = temperature
        self._model: Optional[BaseChatModel] = None

    @property
    def available(self) -> bool:
        return bool(self._api_key)

    def _get_model(self) -> BaseChatModel:
        if self._model is None:
            from langchain_groq import ChatGroq

            self._model = ChatGroq(
                model=self._model_name,
                api_key=self._api_key,
                temperature=self._temperature,
                max_retries=0,  # we own retry/timeout policy
            )
        return self._model

    async def ainvoke(
        self,
        messages: Sequence[BaseMessage],
        *,
        tools: Optional[list] = None,
        config: Optional[RunnableConfig] = None,
    ) -> AIMessage:
        if not self.available:
            raise LLMProviderError(self.provider_name, RuntimeError("GROQ_API_KEY not configured"))

        last_exc: Optional[Exception] = None
        attempts = self._max_retries + 1
        for attempt in range(1, attempts + 1):
            t0 = time.time()
            try:
                model = self._get_model()
                bound = model.bind_tools(tools) if tools else model
                msg = await asyncio.wait_for(
                    bound.ainvoke(messages, config=config), timeout=self._timeout_s
                )
                log.info(f"[LLM] Response generated by Groq ({(time.time() - t0) * 1000:.0f}ms)")
                return msg
            except asyncio.TimeoutError as e:
                last_exc = e
                log.warning(
                    f"[LLM] Groq timed out after {self._timeout_s:.0f}s "
                    f"(attempt {attempt}/{attempts})"
                )
            except Exception as e:  # noqa: BLE001
                last_exc = e
                log.warning(
                    f"[LLM] Groq {classify_error(e)} (attempt {attempt}/{attempts}): {e}"
                )

        raise LLMProviderError(self.provider_name, last_exc or RuntimeError("unknown Groq failure"))

    def invoke(
        self,
        messages: Sequence[BaseMessage],
        *,
        tools: Optional[list] = None,
        config: Optional[RunnableConfig] = None,
    ) -> AIMessage:
        if not self.available:
            raise LLMProviderError(self.provider_name, RuntimeError("GROQ_API_KEY not configured"))

        last_exc: Optional[Exception] = None
        attempts = self._max_retries + 1
        for attempt in range(1, attempts + 1):
            t0 = time.time()
            try:
                model = self._get_model()
                bound = model.bind_tools(tools) if tools else model
                msg = bound.invoke(messages, config=config)
                log.info(f"[LLM] Response generated by Groq ({(time.time() - t0) * 1000:.0f}ms)")
                return msg
            except Exception as e:  # noqa: BLE001
                last_exc = e
                log.warning(
                    f"[LLM] Groq {classify_error(e)} (attempt {attempt}/{attempts}): {e}"
                )
        raise LLMProviderError(self.provider_name, last_exc or RuntimeError("unknown Groq failure"))

    async def health_check(self) -> bool:
        return self.available
